CREATE DATABASE IF NOT EXISTS slip25;
use slip25;
CREATE TABLE Teacher(tid INT(3) PRIMARY KEY, tname VARCHAR(30), address VARCHAR(50), subject VARCHAR(25));
INSERT INTO Teacher VALUES(101,"ABC","INDIA","PHP");
DROP DATABASE slip25;